name: 构建与发布二进制
#https://github.com/ajeetdsouza/zoxide/blob/main/github/workflows/release.yml
#https://github.com/svenstaro/genact/blob/master/:github/workflows/build-release.yml
#https://github.com/svenstaro/miniserve/blob/master/.github/workflows/build-release.yml
env:
  CICD_INTERMEDIATES_DIR: "_cicd-intermediates"
  MSRV_FEATURES: --no-default-features --features minimal-application,bugreport,build-assets
on:
  push:
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  crate_metadata:
    name: 提取元数据
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: 提取 Crate 元数据
        id: crate_metadata
        run: |
          cargo metadata --no-deps --format-version 1 | jq -r '"name=" + .packages[0].name' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"version=" + .packages[0].version' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"maintainer=" + .packages[0].authors[0]' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"homepage=" + .packages[0].homepage' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"msrv=" + .packages[0].rust_version' | tee -a $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.crate_metadata.outputs.name }}
      version: ${{ steps.crate_metadata.outputs.version }}
      maintainer: ${{ steps.crate_metadata.outputs.maintainer }}
      homepage: ${{ steps.crate_metadata.outputs.homepage }}
      msrv: ${{ steps.crate_metadata.outputs.msrv }}
  ensure_cargo_fmt:
    name: 确保 'cargo fmt' 运行
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: actions/checkout@v5
      - run: cargo fmt -- --check

  build:
    name: 🏗️ 构建 ${{ matrix.job.target }}（${{ matrix.job.os }}）
    runs-on: ${{ matrix.job.os }}
    needs: crate_metadata
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: aarch64-unknown-linux-gnu   , os: ubuntu-22.04, use-cross: true }
          - { target: aarch64-unknown-linux-musl  , os: ubuntu-22.04, use-cross: true }
          - { target: arm-unknown-linux-gnueabihf , os: ubuntu-22.04, use-cross: true }
          - { target: arm-unknown-linux-musleabihf, os: ubuntu-22.04, use-cross: true }
          - { target: i686-pc-windows-msvc        , os: windows-2022                  }
          - { target: i686-unknown-linux-gnu      , os: ubuntu-22.04, use-cross: true }
          - { target: i686-unknown-linux-musl     , os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-apple-darwin         , os: macos-13                      }
          - { target: aarch64-apple-darwin        , os: macos-14                      }
          - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
          - { target: x86_64-pc-windows-msvc      , os: windows-2022                  }
          - { target: aarch64-pc-windows-msvc     , os: windows-11-arm                }
          - { target: x86_64-unknown-linux-gnu    , os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-unknown-linux-musl   , os: ubuntu-22.04, use-cross: true }
    env:
      BUILD_CMD: cargo
    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v5

      - name: 🔧 安装前置依赖
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            arm-unknown-linux-*) sudo apt-get -y update ; sudo apt-get -y install gcc-arm-linux-gnueabihf ;;
            aarch64-unknown-linux-gnu) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu ;;
          esac

      - name: 🦀 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: 📦 安装 cross
        if: matrix.job.use-cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: 🧩 覆盖构建命令环境变量
        if: matrix.job.use-cross
        shell: bash
        run: echo "BUILD_CMD=cross" >> $GITHUB_ENV

      - name: ℹ️ 显示版本信息（Rust、Cargo、GCC）
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V
      - name: 🛠️ 构建
        shell: bash
        run: $BUILD_CMD build --locked --release --target=${{ matrix.job.target }}
#        env:
#          OPENSSL_NO_VENDOR: "1"
      - name: 🏷️ 设置二进制名称与路径
        id: bin
        shell: bash
        run: |
          # Figure out suffix of binary
          EXE_suffix=""
          case ${{ matrix.job.target }} in
            *-pc-windows-*) EXE_suffix=".exe" ;;
          esac;
          
          # Setup paths
          BIN_NAME="${{ needs.crate_metadata.outputs.name }}${EXE_suffix}"
          BIN_PATH="target/${{ matrix.job.target }}/release/${BIN_NAME}"
          
          # Let subsequent steps know where to find the binary
          echo "BIN_PATH=${BIN_PATH}" >> $GITHUB_OUTPUT
          echo "BIN_NAME=${BIN_NAME}" >> $GITHUB_OUTPUT

      - name: ⚙️ 设置测试选项
        id: test-options
        shell: bash
        run: |
          # test only library unit tests and binary for arm-type targets
          unset CARGO_TEST_OPTIONS
          unset CARGO_TEST_OPTIONS ; case ${{ matrix.job.target }} in arm-* | aarch64-*) CARGO_TEST_OPTIONS="--bin ${{ needs.crate_metadata.outputs.name }}" ;; esac;
          echo "CARGO_TEST_OPTIONS=${CARGO_TEST_OPTIONS}" >> $GITHUB_OUTPUT

      - name: ✅ 运行测试
        shell: bash
        run: |
          if [[ ${{ matrix.job.os }} = windows-* ]]
          then
          powershell.exe -command "$BUILD_CMD test --locked --target=${{ matrix.job.target }} ${{ steps.test-options.outputs.CARGO_TEST_OPTIONS}}"
          else
          $BUILD_CMD test --locked --target=${{ matrix.job.target }} ${{ steps.test-options.outputs.CARGO_TEST_OPTIONS}}
          fi


      - name: 📦 生成归档包
        id: package
        shell: bash
        run: |
          PKG_suffix=".tar.gz" ; case ${{ matrix.job.target }} in *-pc-windows-*) PKG_suffix=".zip" ;; esac;
          PKG_BASENAME=${{ needs.crate_metadata.outputs.name }}-v${{ needs.crate_metadata.outputs.version }}-${{ matrix.job.target }}
          PKG_NAME=${PKG_BASENAME}${PKG_suffix}
          echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_OUTPUT
          
          PKG_STAGING="${{ env.CICD_INTERMEDIATES_DIR }}/package"
          ARCHIVE_DIR="${PKG_STAGING}/${PKG_BASENAME}/"
          mkdir -p "${ARCHIVE_DIR}"
          
          # Binary
          cp "${{ steps.bin.outputs.BIN_PATH }}" "$ARCHIVE_DIR"
          
          # README, LICENSE and CHANGELOG files
          cp "README.md"  "$ARCHIVE_DIR"
          
          
          # Autocompletion files
          
          # base compressed package
          pushd "${PKG_STAGING}/" >/dev/null
          case ${{ matrix.job.target }} in
            *-pc-windows-*) 7z -y a "${PKG_NAME}" "${PKG_BASENAME}"/* | tail -2 ;;
            *) tar czf "${PKG_NAME}" "${PKG_BASENAME}"/* ;;
          esac;
          popd >/dev/null
          
          # Let subsequent steps know where to find the compressed package
          echo "PKG_PATH=${PKG_STAGING}/${PKG_NAME}" >> $GITHUB_OUTPUT

      - name: "⬆️ 上传构件：归档包"
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.package.outputs.PKG_NAME }}
          path: ${{ steps.package.outputs.PKG_PATH }}

      - name: 🔎 检查是否需要发布
        id: is-release
        shell: bash
        run: |
          unset IS_RELEASE ; if [[ $GITHUB_REF =~ ^refs/tags/v[0-9].* ]]; then IS_RELEASE='true' ; fi
          echo "IS_RELEASE=${IS_RELEASE}" >> $GITHUB_OUTPUT
      - name: 📄 生成变成日志
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feature"]
                },
                {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix"]
                },
                {
                    "title": "## 🧪 Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 发布归档与安装包
        uses: softprops/action-gh-release@v2
        if: steps.is-release.outputs.IS_RELEASE
        with:
          body: ${{ steps.changelog.outputs.body }}
          files: |
            ${{ steps.package.outputs.PKG_PATH }}
            ${{ steps.debian-package.outputs.DPKG_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  winget:
#    name: 发布到 Winget
#    runs-on: ubuntu-latest
#    needs: build
#    if: startsWith(github.ref, 'refs/tags/v')
#    steps:
#      - uses: vedantmgoyal2009/winget-releaser@v2
#        with:
#          identifier: jiqinga.nacos-tpl
#          installers-regex: '-pc-windows-msvc\.zip$'
#          token: ${{ secrets.WINGET_TOKEN }}
